name: Build Python Service
on:
  workflow_dispatch:
env:
  RECOMMENDATION_PORT: 1010
  OTEL_SERVICE_NAME: recommendation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
            cd src/recommendation
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Build
        run: |
            opentelemetry-bootstrap -a install
            cd src/recommendation
            python recommendation_server.py