name: Build Java Service
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: |
          cd src/ad
          ./gradlew
          ./gradlew downloadRepos
          ./gradlew installDist -PprotoSourceDir=./proto